TercerosCambios
SG-SantiagoGilgorri/nextjs-Presentacion pull request #3
Opened 2023-06-16 03:11 UTC by SG-SantiagoGilgorri

1- Realice cambios de CSS sobre el contenedor del clima (No pude con tailwind, despues lo vemos)
2- Cambie el favicon y el title.
3-Instale Prettier y aplique arreglos sobre index.js, page.js, y temperatura.jsx (se tiene que hacer en los componentes CSS??)

pd: amigo te tenia que preguntar sobre ESlint porque tengo algunas dudas..... como por ejemplo que mi app ya tiene un archivo .eslintrc.json que yo nunca instale y al parecer viene con next.

y despues segun lo que vi hay algunas iteraciones de prettier que chocan con las de ESlint por eso es clave configurarlos bien (y te iba a pedir ayuda) 
Prettier me parecio bastante bueno y sencillo. apuntas al directorio ejecutas comando y te lo ordena !!una locura!! 

Buen dia para vos amigo y que tengas linda mañana!!!

2023-06-16 07:49 UTC, joacoc requested changes
1. El estilo del weather esta medio raro. Seguramente sea por las dimensiones de tu pantalla comparadas a la mía. Fíjate como se ven en la mía que es mas chica:

<img width="1440" alt="Screenshot 2023-06-16 at 09 39 13" src="https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/assets/11491779/ce8e2cff-04dc-4a8a-b5dc-ad38f898a957">


2. El `favicon.ico` lo tienes que cargar en la function que se llama `RootLayout`:

Agrégale esto al html:

```javascript
      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
```

2023-06-16 07:49 UTC, joacoc commented on app/page.js
> +      <Image className={style.img} src="/avatar.jpg" width={205} height={205} />
Tu imagen debería estar centrada en el `<div/>` actualmente esta tirada para la izquierda

2023-06-16 07:49 UTC, joacoc commented on app/page.js
> +      <h1 className={style.card}>Gilgorri Santiago</h1>
Lo mismo sucede con el nombre

2023-06-16 07:49 UTC, joacoc commented on app/page.js
> +      <h2 className={style.card}>Santiagogilgorri@gmail.com</h2>
Agregale el icono de Email y fíjate que tiene un exceso en el `width`:
<img width="1390" alt="Screenshot 2023-06-16 at 09 46 32" src="https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/assets/11491779/e8365e0e-e183-46ae-96a0-2dff40d8ebd4">

Lo podemos ver juntos si queres!

2023-06-16 07:49 UTC, joacoc commented on app/page.js
> +        <h2 className={style.card}>https://github.com/SG-SantiagoGilgorri</h2>
Agregale el logo de Github 🐈

2023-06-16 07:49 UTC, joacoc commented on app/temperatura.jsx
> +    <main>
El main solo se utiliza una vez en toda la pagina. El que esta en `page.js` es suficiente! Lo podes remover tranquilamente este:
```suggestion
```

2023-06-16 07:50 UTC, joacoc commented
> y despues segun lo que vi hay algunas iteraciones de prettier que chocan con las de ESlint y no me quedo del todo claro si tengo que configurar algo...

Si, hay que configurar por que chocan y es un garron! No me acuerdo en este momento cual es la config que choca.

2023-06-16 17:09 UTC, SG-SantiagoGilgorri commented on app/page.js
> +      <h2 className={style.card}>Santiagogilgorri@gmail.com</h2>
Amigo estoy con esto y con lo del <div> que me indicaste arriba, no le termino de agarrar la vuelta,
el logo de github ya lo puse al igual que el favicon

2023-06-16 18:49 UTC, joacoc commented on app/page.js
> +      <h2 className={style.card}>Santiagogilgorri@gmail.com</h2>
> no le termino de agarrar la vuelta

Como seria esto? Pásame el issue que tienes y como luce el código!

2023-06-16 19:55 UTC, SG-SantiagoGilgorri commented
Amigo hice todo lo del request, tenia una duda en particular sobre el :

2- El favicon.ico lo tienes que cargar en la function que se llama RootLayout:

Agrégale esto al html:

      <head>
        <link rel='icon' href='/favicon.ico'/>
      </head>
      
      
      
 lo hice pero nose si esta bien "./app/layout.js" linea 15,16,17

2023-06-18 23:19 UTC, SG-SantiagoGilgorri commented
Amigo no vi el merge asi que volvi a pushear sobre el mismo branch otro pull request

te comento que tuve que cambiar el contenedor del clima porque con el otro no puedo hacerle Reactivness

tenia que resolver 2 dudas mañana en la call lo vemos una es que el link del github para hacer click me toma mas espacio que las dimensiones de la carta
![imagen](https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/assets/129072570/c7e99eeb-f2ca-4b1c-9103-53f51cc2854b)

y despues lo segundo que el contenedor para el clima que elegi usa bootstrap y hay iconos.png que no me lo esta tomando nose si hice bien la install

2023-06-19 07:41 UTC, joacoc requested changes
En la daily

2023-06-19 07:41 UTC, joacoc commented on app/page.js
> +      <h2 className={style.card}>Santiagogilgorri@gmail.com</h2>
La mayúscula puede traer problemas para el email!
```suggestion
      <h2 className={style.card}>santiagogilgorri@gmail.com</h2>
```

2023-06-19 07:41 UTC, joacoc commented on app/temperatura.jsx
> +    <div className={style.weatherCard}>
Esto lo vemos hoy en la call. Si no funciona, mándale otro weather que te guste mas o que funcione!

2023-06-22 02:27 UTC, SG-SantiagoGilgorri commented
Amigoo elegi un widget del clima que usa tailwind y lo hice andar, aparte de que ajuste linealmente todos los componentes.

ahora.... estoy teniendo un problema para que cambie el icono del clima en el contenedor ya que no son imagenes sino que son tags: <svg> <path> <rect> y nose si entendi bien pero son rectangulos que se van transformando... en fin no pude solucionarlo

![imagen](https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/assets/129072570/13ec231e-1d2e-4d75-8ab2-b084c0d77da2)


Pd: trate de linkearte como me enseñaste pero el branch no esta mergeado y esta desactualizado asi que te pase la captura

2023-06-22 08:43 UTC, joacoc commented
Podes acceder al código de tu branch por acá:

<img width="461" alt="Screenshot 2023-06-22 at 10 36 22" src="https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/assets/11491779/a88dd3c0-5a35-4a21-b885-06efabfb5519">

Los `<svg>` son vectores que la compu dibuja y hace imágenes. (Le decís a la maquina dibuja desde este punto hasta este punto una linea gris y listo). Por lo que veo solo tenes cargado el [svg del sol](https://github.com/SG-SantiagoGilgorri/nextjs-Presentacion/blob/32788b15ab79da4d78dfa18a06b085106935c915/app/temperatura.jsx#L29). Lo que tendrías que hacer es.

Código de ejemplo:
`
let svg;
if (soleado) {
 svg = svgsoleado 
} else if (nublado) {
svg = svgnublado
}


return (
    <div className=" ml-16 flex flex-col items-center p-8 rounded-md w-60 sm:px-12 dark:bg-gray-900 dark:text-gray-100">
      <div className="text-center">
        <h2 className="text-xl font-semibold">Mar del plata</h2>
        <p className="text-sm dark:text-gray-400">Argentina</p>
      </div>
      {svg}
      ...
)
`

2023-07-05 12:52 UTC, merged

2023-07-05 13:06 UTC, joacoc commented
@SG-SantiagoGilgorri le podes meter en una card a la temperatura tmb.